channels:
  - conda-forge
dependencies:
  - python=3.8.3
  - r-base=3.6.3
  - r-ggplot2
  # Python dependencies
  - rpy2=3.3.6
  - matplotlib
  - pandas
  - plotnine
  - ipycytoscape
  - nglview
  - itkwidgets
  - widgetsnbextension
  - jupyter-lsp
  - jupyter-lsp-python
  - jupyterlab